[tools]
cargo-binstall = "latest"
flutter = "latest"
go = "latest"
node = "latest"
pnpm = "latest"
ruby = "latest"
rust = "stable"
slsa-verifier = "latest"
yarn = "1"
zig = "latest"
cosign = "latest"
"cargo:cargo-outdated" = "latest"
bun = "latest"
pipx = "latest"
usage = "latest"

[settings]
disable_hints = ["registry"]
disable_tools = ["python"]
